# Generated by Django 3.2.7 on 2021-09-13 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investimentos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acao',
            old_name='nome',
            new_name='sigla',
        ),
    ]
