# Generated by Django 3.2.7 on 2021-09-18 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investimentos', '0002_rename_nome_acao_sigla'),
    ]

    operations = [
        migrations.AddField(
            model_name='acao',
            name='sigla_corrigida',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='acao',
            name='sigla',
            field=models.CharField(max_length=6, unique=True),
        ),
        migrations.CreateModel(
            name='ValorAcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_referencia', models.DateField()),
                ('valor_abertura', models.FloatField()),
                ('valor_fechamento', models.FloatField()),
                ('volume', models.FloatField()),
                ('acao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investimentos.acao')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioAcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_adicao', models.DateField()),
                ('data_atualizacao', models.DateField()),
                ('data_inicio_acompanhamento', models.DateField()),
                ('acao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investimentos.acao')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
